### ISSUE TITLE
Button Error - Big Time

### ISSUE THREAD

**Issue by EvanVet** [badsha-eee/Change-WooCommerce-Add-to-Cart-Text#1]
Make the button do this....

![screen shot 2018-07-11 at 1 00 12 pm](https://user-images.githubusercontent.com/41096978/42548539-dc875716-850a-11e8-9ace-8df9f797d8fb.png)

**Comment by sekanderb** [comment]
Hello @fleamail,

I am sorry to inform you that I am not maintaining this plugin anymore. WooCommerce changed their codebase. So this plugin is incompatible now.

You can try this one https://wordpress.org/plugins/wc-custom-add-to-cart-labels/
Or search "change add to cart button text woocommerce"
